version: 2
jobs:
  test:
    docker:
      - image: node:9.5.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Create Reports Folder
          command: mkdir -p ./reports

      - run:
          name: Install Deps
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Code Style Lint
          command: yarn check-style

      - run:
          name: Lint
          command: yarn lint

workflows:
  version: 2
  test:
    jobs:
      - test
